/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from 'next/link'
import { redirect } from 'next/navigation'
import { getCurrentUser } from '@/lib/auth'
import { createClient } from '@/lib/supabase/server'
import { createEventAction, createGalleryPhotoAction, createGameAction, createSeasonAction, createTeamRankingAction, deleteContentAction, saveGalleryAction } from './actions'
import styles from './page.module.scss'

function DeleteButton({ table, id }: { table: string; id: string }) { return <form action={deleteContentAction}><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={id}/><button className={styles.delete}>Remover</button></form> }

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ erro?: string; mensagem?: string }> }) {
  const user = await getCurrentUser(); if (!user) redirect('/login'); if (user.role !== 'admin') redirect('/perfil')
  const supabase = await createClient()
  const [{ data: games }, { data: seasons }, { data: events }, { data: photos }] = await Promise.all([
    supabase.from('games').select('id,name').order('display_order'), supabase.from('ranking_seasons').select('id,label,games(name)').order('created_at', { ascending: false }), supabase.from('events').select('id,title,starts_at').order('display_order'), supabase.from('gallery_photos').select('id,alt_text').order('display_order'),
  ])
  const params = await searchParams
  return <main className={styles.page}><div className={styles.shell}><header className={styles.top}><div><Link href="/"><img src="/images/logo.png" alt="FEGEPI" /></Link><h1>Painel administrativo</h1><p>Publique o conteÃºdo que aparece na pÃ¡gina inicial.</p></div><Link className={styles.back} href="/perfil">â† Meu perfil</Link></header>{params.erro && <p className={`${styles.notice} ${styles.error}`}>{params.erro}</p>}{params.mensagem && <p className={`${styles.notice} ${styles.success}`}>{params.mensagem}</p>}<div className={styles.grid}>
  <section className={styles.card}><h2>Jogos do ranking</h2><p className={styles.hint}>Cadastre o jogo e depois crie sua temporada.</p><form action={createGameAction} className={styles.form} encType="multipart/form-data"><input name="name" required placeholder="Nome do jogo"/><div className={styles.pair}><input name="shortName" placeholder="Sigla (ex.: CS2)"/><select name="theme" defaultValue="cs2"><option value="cs2">CS2</option><option value="valorant">Valorant</option><option value="lol">League of Legends</option><option value="freefire">Free Fire</option><option value="fc26">FC 26</option></select></div><input name="imageUrl" type="url" placeholder="URL da imagem (ou envie abaixo)"/><input name="image" type="file" accept="image/*"/><input name="displayOrder" type="number" defaultValue="0" placeholder="Ordem"/><button className={styles.submit}>Cadastrar jogo</button></form><div className={styles.list}>{(games ?? []).map((game: any) => <div className={styles.row} key={game.id}><span>{game.name}</span><DeleteButton table="games" id={game.id}/></div>)}</div></section>
  <section className={styles.card}><h2>Temporada</h2><p className={styles.hint}>A temporada reÃºne os times e a pontuaÃ§Ã£o de cada jogo.</p><form action={createSeasonAction} className={styles.form}><select name="gameId" required defaultValue=""><option value="" disabled>Selecione o jogo</option>{(games ?? []).map((game: any) => <option key={game.id} value={game.id}>{game.name}</option>)}</select><input name="label" required placeholder="Ex.: Temporada 2026"/><label className={styles.check}><input name="isCurrent" type="checkbox"/> Temporada atual</label><button className={styles.submit}>Criar temporada</button></form><div className={styles.list}>{(seasons ?? []).map((season: any) => <div className={styles.row} key={season.id}><span>{season.games?.name} â€” {season.label}</span><DeleteButton table="ranking_seasons" id={season.id}/></div>)}</div></section>
  <section className={styles.card}><h2>Times e pontuaÃ§Ã£o</h2><p className={styles.hint}>Inclui o time diretamente na temporada escolhida.</p><form action={createTeamRankingAction} className={styles.form} encType="multipart/form-data"><select name="seasonId" required defaultValue=""><option value="" disabled>Selecione a temporada</option>{(seasons ?? []).map((season: any) => <option key={season.id} value={season.id}>{season.games?.name} â€” {season.label}</option>)}</select><div className={styles.pair}><input name="teamName" required placeholder="Nome do time"/><input name="city" placeholder="Cidade"/></div><div className={styles.pair}><input name="initials" maxLength={4} placeholder="Sigla"/><input name="crestUrl" type="url" placeholder="URL do escudo"/></div><input name="crest" type="file" accept="image/*"/><div className={styles.pair}><input name="points" type="number" min="0" defaultValue="0" placeholder="Pontos"/><input name="previousPosition" type="number" min="0" defaultValue="0" placeholder="PosiÃ§Ã£o anterior"/></div><button className={styles.submit}>Adicionar ao ranking</button></form></section>
  <section className={styles.card}><h2>Eventos</h2><p className={styles.hint}>A imagem de destaque pode ser vÃ­deo (.mp4) ou imagem.</p><form action={createEventAction} className={styles.form} encType="multipart/form-data"><input name="title" required placeholder="TÃ­tulo do evento"/><div className={styles.pair}><input name="startsAt" type="date" required/><input name="endsAt" type="date"/></div><input name="subtitle" placeholder="SubtÃ­tulo"/><div className={styles.pair}><input name="statusLabel" placeholder="Ex.: InscriÃ§Ãµes abertas"/><select name="statusTone" defaultValue="active"><option value="active">Ativo</option><option value="inactive">Em breve</option></select></div><input name="imageUrl" type="url" placeholder="URL da imagem"/><input name="image" type="file" accept="image/*"/><input name="featuredUrl" type="url" placeholder="URL de mÃ­dia de destaque (opcional)"/><input name="featured" type="file" accept="image/*,video/mp4"/><input name="registrationUrl" type="url" placeholder="Link de inscriÃ§Ã£o"/><div className={styles.pair}><input name="ctaLabel" placeholder="Texto do botÃ£o"/><input name="displayOrder" type="number" defaultValue="0" placeholder="Ordem"/></div><button className={styles.submit}>Publicar evento</button></form><div className={styles.list}>{(events ?? []).map((event: any) => <div className={styles.row} key={event.id}><span>{event.title} â€” {event.starts_at}</span><DeleteButton table="events" id={event.id}/></div>)}</div></section>
  <section className={`${styles.card} ${styles.wide}`}><h2>Galeria do Ãºltimo evento</h2><p className={styles.hint}>Atualize a capa e acrescente as fotos disponÃ­veis para download.</p><form action={saveGalleryAction} className={styles.form} encType="multipart/form-data"><div className={styles.pair}><input name="eyebrow" placeholder="Texto menor" defaultValue="Quem nos apoia"/><input name="title" placeholder="TÃ­tulo da seÃ§Ã£o" defaultValue="Fotos do Ãºltimo evento"/></div><input name="bannerTitle" placeholder="TÃ­tulo da capa"/><textarea name="bannerDescription" placeholder="DescriÃ§Ã£o da capa"/><input name="bannerAlt" placeholder="DescriÃ§Ã£o acessÃ­vel da imagem"/><input name="bannerUrl" type="url" placeholder="URL da imagem de capa"/><input name="banner" type="file" accept="image/*"/><button className={styles.submit}>Salvar capa</button></form><form action={createGalleryPhotoAction} className={styles.form} encType="multipart/form-data" style={{ marginTop: 24 }}><input name="alt" placeholder="DescriÃ§Ã£o da foto"/><input name="downloadUrl" type="url" placeholder="URL de download (opcional)"/><input name="imageUrl" type="url" placeholder="URL da foto"/><input name="image" type="file" accept="image/*"/><input name="displayOrder" type="number" defaultValue="0" placeholder="Ordem"/><button className={styles.submit}>Adicionar foto</button></form><div className={styles.list}>{(photos ?? []).map((photo: any) => <div className={styles.row} key={photo.id}><span>{photo.alt_text}</span><DeleteButton table="gallery_photos" id={photo.id}/></div>)}</div></section>
</div></div></main>
}

